In [1]:
import torch

In [2]:
x=torch.rand(3,4,4)

In [3]:
x

tensor([[[0.5189, 0.6680, 0.9217, 0.7152],
         [0.5689, 0.8132, 0.2674, 0.3161],
         [0.8882, 0.2553, 0.9967, 0.3614],
         [0.1259, 0.0539, 0.9845, 0.7904]],

        [[0.4813, 0.0842, 0.9917, 0.5815],
         [0.9890, 0.9041, 0.8729, 0.1663],
         [0.1302, 0.4863, 0.1196, 0.5822],
         [0.9919, 0.3335, 0.7682, 0.4633]],

        [[0.3343, 0.9179, 0.2294, 0.6455],
         [0.4652, 0.0848, 0.7145, 0.8706],
         [0.5579, 0.3165, 0.6842, 0.8458],
         [0.6760, 0.4086, 0.8333, 0.6689]]])

In [4]:
img=torch.rand(size=(224,224,3))

In [5]:
x=torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x=torch.ones_like(x)

In [7]:
x

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

*  add 
* sub
* multiplication
* divison 
*  elemnet wise
* matrxi multiplication

In [8]:
#maniplulationTEnsor:
ten=torch.tensor([1,2,3])

AttributeError: module 'torch' has no attribute 'te'